include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test

code_quality:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
  services:
  tags:
    - cq-sans-dind
